# Generated by Django 3.2.20 on 2023-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker_jira', '0002_auto_20231008_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraconnection',
            name='api_url',
            field=models.CharField(default='https://sjira.funkemedien.de', max_length=200, verbose_name='API URL'),
        ),
        migrations.AlterField(
            model_name='jiraconnection',
            name='story_points_field',
            field=models.CharField(default='customfield_10702', max_length=200, verbose_name='Story Points Field'),
        ),
    ]
